config/routes.rb
K9calendar::Application.routes.draw do
  resources :bookings

  resources :breeds

  resources :dogs

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :dog
  attr_accessible :date, :dog_id
  validates :date, :presence => true
  validates :dog_id, :presence => true
end

app/models/breed.rb
class Breed < ActiveRecord::Base
  attr_accessible :name
  has_many :dogs
  validates :name, :presence => true, :uniqueness => true
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  attr_accessible :jumps_fences, :name, :breed_id, :notes, :weight
  belongs_to :breed
  validates :breed_id, :presence => true
  validates :name, :presence => true
  validates :weight, :inclusion => { :in => 1..200, :message => "must be between 1 and 200" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all(order: 'date')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookings }
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(params[:booking])

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { render action: "new" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  # GET /breeds
  # GET /breeds.json
  def index
    @breeds = Breed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @breeds }
    end
  end

  # GET /breeds/1
  # GET /breeds/1.json
  def show
    @breed = Breed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @breed }
    end
  end

  # GET /breeds/new
  # GET /breeds/new.json
  def new
    @breed = Breed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @breed }
    end
  end

  # GET /breeds/1/edit
  def edit
    @breed = Breed.find(params[:id])
  end

  # POST /breeds
  # POST /breeds.json
  def create
    @breed = Breed.new(params[:breed])

    respond_to do |format|
      if @breed.save
        format.html { redirect_to @breed, notice: 'Breed was successfully created.' }
        format.json { render json: @breed, status: :created, location: @breed }
      else
        format.html { render action: "new" }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /breeds/1
  # PUT /breeds/1.json
  def update
    @breed = Breed.find(params[:id])

    respond_to do |format|
      if @breed.update_attributes(params[:breed])
        format.html { redirect_to @breed, notice: 'Breed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @breed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breeds/1
  # DELETE /breeds/1.json
  def destroy
    @breed = Breed.find(params[:id])
    @breed.destroy

    respond_to do |format|
      format.html { redirect_to breeds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dogs }
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dog = Dog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dog }
    end
  end

  # GET /dogs/new
  # GET /dogs/new.json
  def new
    @dog = Dog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dog }
    end
  end

  # GET /dogs/1/edit
  def edit
    @dog = Dog.find(params[:id])
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(params[:dog])

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render json: @dog, status: :created, location: @dog }
      else
        format.html { render action: "new" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dogs/1
  # PUT /dogs/1.json
  def update
    @dog = Dog.find(params[:id])

    respond_to do |format|
      if @dog.update_attributes(params[:dog])
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    respond_to do |format|
      format.html { redirect_to dogs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/bookings/_form.html.erb
<%= form_for @booking, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Booking</legend>

    <div class="control-group">
      <%= f.label :date, :class => 'control-label' %>
      <div class="controls">
        <%= f.date_select :date, :class => 'date_select' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :dog_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.select("dog_id", Dog.all.collect {|dog| [ dog.name, dog.id ] }, { :include_blank => true }) %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btna-primary' %>
      <%= link_to 'Cancel', bookings_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/bookings/edit.html.erb
<%= render :partial => 'form' %>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Dog</th>
      <th>Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.dog.try(:name) %></td>
        <td><%= link_to booking.date, booking_path(booking) %></td>
        <td>
          <%= link_to 'Edit', edit_booking_path(booking), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', booking_path(booking), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_booking_path, :class => 'btn btn-primary' %>

app/views/bookings/new.html.erb
<%= render :partial => 'form' %>

app/views/bookings/show.html.erb
<h1>Booking</h1>

<p>
  <b>Date</b><br>
  <%= @booking.date %>
</p>

<p>
  <b>Dog</b><br>
  <%= @booking.dog.try(:name) %>
</p>

<div class="form-actions">
  <%= link_to 'Back', bookings_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_booking_path(@booking), :class => 'btn' %>
  <%= link_to 'Delete', booking_path(@booking), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/breeds/_form.html.erb
<%= form_for @breed, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @breed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breed.errors.count, "error") %> prohibited this breed from being saved:</h2>

      <ul>
      <% @breed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<fieldset>
    <legend><%= controller.action_name.capitalize %> Breed</legend>
	  <div class="control-group">
	    <%= f.label :name, :class => 'control-label' %><br />
			<div class="controls">
	    	<%= f.text_field :name, :class => 'string_select' %>
			</div>
	  </div>
	
	  <div class="form-actions">
      <%= f.submit nil, :class => 'btn btna-primary' %>
      <%= link_to 'Cancel', breeds_path, :class => 'btn' %>
    </div>
	</fieldset>
<% end %>

app/views/breeds/edit.html.erb
<h1>Editing breed</h1>

<%= render 'form' %>

<%= link_to 'Show', @breed %> |
<%= link_to 'Back', breeds_path %>

app/views/breeds/index.html.erb
<h1>Listing breeds</h1>

<table class="table table-striped">
	 <thead>
  	<tr>
	    <th>Name</th>
	    <th>Actions</th>
	  </tr>
  </thead>
	
  <tbody>
		<% @breeds.each do |breed| %>
		  <tr>
		    <td><%= breed.name %></td>
		    <td><%= link_to 'Show', breed %></td>
		    <td><%= link_to 'Edit', edit_breed_path(breed), :class => 'btn btn-mini' %></td>
		    <td><%= link_to 'Destroy', breed, :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger'%></td>
		  </tr>
		<% end %>
	<tbody>
</table>

<br />

<%= link_to 'New', new_breed_path, :class => 'btn btn-primary' %>

app/views/breeds/new.html.erb
<h1>New breed</h1>

<%= render 'form' %>

<%= link_to 'Back', breeds_path %>

app/views/breeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @breed.name %>
</p>

<div class="form-actions">
	<%= link_to 'Edit', edit_breed_path(@breed), :class => 'btn' %> |
	<%= link_to 'Back', breeds_path, :class => 'btn'  %>
</div>

app/views/dogs/_form.html.erb
<%= form_for @dog, :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> /Dog</legend>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :breed_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.select("breed_id", Breed.all.collect {|breed| [ breed.name, breed.id ] }, { :include_blank => true }) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :weight, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :weight, :class => 'number_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :notes, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :notes, :class => 'text_area' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :jumps_fences, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :jumps_fences, :class => 'check_box' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', dogs_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/dogs/edit.html.erb
<%= render :partial => 'form' %>

app/views/dogs/index.html.erb
<h1>Dogs</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.id %></td>
        <td><%= link_to dog.name, dog_path(dog) %></td>
        <td><%= dog.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_dog_path(dog), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', dog_path(dog), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_dog_path, :class => 'btn btn-primary' %>

app/views/dogs/new.html.erb
<%= render :partial => 'form' %>

app/views/dogs/show.html.erb
<h1>/Dog</h1>

<p>
  <b>Name</b><br>
  <%= @dog.name %>
</p>

<p>
  <b>Weight</b><br>
  <%= @dog.weight %>
</p>

<p>
  <b>Notes</b><br>
  <%= @dog.notes %>
</p>

<p>
  <b>Jumps fences</b><br>
  <%= @dog.jumps_fences %>
</p>

<p>
  <b>Breed</b><br>
  <%= @dog.breed_id %>
</p>

<div class="form-actions">
  <%= link_to 'Back', dogs_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_dog_path(@dog), :class => 'btn' %>
  <%= link_to 'Delete', dog_path(@dog), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>K9calendar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">K9 Calendar</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Bookings", bookings_path %></li>
          <li><%= link_to "Dogs", dogs_path %></li>
          <li><%= link_to "Breeds", breeds_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>